### PR TITLE
Update from openwrt/openwrt on 1 Sep 2024

### PR DESCRIPTION
**Pull request by aywl1207**

### CODE REVIEW

**Comment by ubernupe** [comment]
Can you add `CONFIG_PACKAGE_ipq-wifi` for `dynalink_dl-wrx36`
I built for my dynalink_dl-wrx36 using your repo - and there were no
wireless settings - and I imagine wireless modules
Thanks

I am @directnupe on OpenWRT Forum - you can PM there as well - I would love to speak with you about your Build

**Comment by aywl1207** [comment]
> Can you add `CONFIG_PACKAGE_ipq-wifi` for `dynalink_dl-wrx36` I built for my dynalink_dl-wrx36 using your repo - and there were no wireless settings - and I imagine wireless modules Thanks
> 
> I am @directnupe on OpenWRT Forum - you can PM there as well - I would love to speak with you about your Build

Hi, my config file has already included CONFIG_PACKAGE_ipq-wifi-dynalink_dl-wrx36=m in MEM_1024 profile which as same as @AgustinLorenzo repo. Since I do not have dynalink_dl-wrx36 to test. You may check with his repo and see if his repo can fit your device or not, thanks.

**Comment by ubernupe** [comment]
Dear aywl1207,
Hello and I hope that you are well. Thank you for getting back to me so swiftly. Just to be sure - you put me on the correct path. 
However, 
`[2024-09-02-0716 | Updated prebuilt images for devices with 512M memory profile (NSS-WiFi)](https://github.com/aywl1207/openwrt-ipq807x/releases/tag/ipq807x-nsswifi-512M-2024-09-02-0716)`
is the Build - along with the `config file` that includes   `CONFIG_PACKAGE_ipq-wifi-dynalink_dl-wrx36=m` - I have triple checked
this in order to verify my findings

The other Build - on the hand -
`[2024-09-02-0720 | Updated prebuilt images for devices with 1G memory profile (NSS-WiFi)](https://github.com/aywl1207/openwrt-ipq807x/releases/tag/ipq807x-nsswifi-1G-2024-09-02-0720)`

Does not - I repeat - does not include `CONFIG_PACKAGE_ipq-wifi-dynalink_dl-wrx36=m`

I have triple checked this as well.

So thank you for pointing me in the right direction - as to the fact that one of your Builds includes 
`CONFIG_PACKAGE_ipq-wifi-dynalink_dl-wrx36=m`  while the other does not

My issue / problem occurred because I used the `config file` without `CONFIG_PACKAGE_ipq-wifi-dynalink_dl-wrx36=m`

One last thing - can you please add `CONFIG_PACKAGE_ipq-wifi-dynalink_dl-wrx36=m` to the MEM_1024 profile 

Thanks and Peace

**Comment by aywl1207** [comment]
Hello @ubernupe, Thank you for your response. I have been utilizing make menuconfig to configure the MEM_* profile. Upon thorough review, I can confirm that once the target device is selected, the related ipq-wifi module is automatically included. Despite several attempts, I have observed that the module cannot be removed unless the build target device is unselected.

Regarding the issue you mentioned, I realized that I had not been removing unnecessary modules for unselected target models, leading them to appear in config.buildinfo.

I am planning to upload an updated release build today based on the modifications made to the MEM_* profile. Please feel free to test the latest build. For more effective troubleshooting, if you encounter issues with my release, consider trying @AgustinLorenzo's build version and testing again. If @AgustinLorenzo's version works while mine does not, kindly report this in the discussion section for further assistance. 

Thanks again~

**Pull request merged**
